title: Abigail Wairimu 
logo: 
description:
  I am a Final year Computer Science Undergraduate student at the Catholic University of Eastern Africa.Dedicated to learning from data and designing AI solutions to social problems.
  <br><br>
  I am currently working with @OmdenaAI as a machine learning Engineer with a keen interest in Natural Language Processing (NLP) and  Recommendation systems.
  <br><br>
  <a href="https://www.linkedin.com/in/abigail-wairimu-3576b3183/">LinkedIn</a> 
  <a href="https://public.tableau.com/app/profile/abigail.wairimu">Tableau</a> 
  <a href="https://github.com/Gail529">Github</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
